PyPSA/atlite

- atlite/convert.py
- setup.py
due to changes made by xarray and pandas
> convert: update resample method details

- README.rst
- atlite/datasets/era5.py
Thank you for updating to the CDS API for ERA5! @coroa 
Since you kind of beat me to it, I figured I'll at least provide the comments
I added to the code while coding my own version.
> Include comments on ERA5 dataset download

- atlite/resource.py
Just a simple addition to warn users if the choosen parameters are causing an 'oversmoothed' power curve with P(0 m/s) > 1e-2, where the 1e-2 are just an arbitrary, IMHO reasonable, value at this point.
I was struggling with too high generation for the past days and don't want anyone to have to drill down this rabbit hole again.
**Why only a warning?**
One can argue that in certain situations oversmoothing is desirable or reasonable.
> Warn user of oversmoothed wind power curves.

- .vscode/settings.json
- doc/installation.rst
> documentation for atlite installation

- atlite/config.py
Following up on #43 .
I will make sure to include this feature into the documentation branch as well.
> config: Allow more formats for configuration updates.

- .gitignore
- test/test_cutout_creation.py
- test/test_cutout_preparation.py
As mentioned in #66, we need some tests which can checked on the run. This PR introduces the first test scripts and will be extended further
Type
```bash
cd path/to/atlite
pytest
```
to run them. 
(Should have named the branch testing)
> Add test scripts

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
This PR introduces templates of issues and pull requests.
Content: see above.
Implemented with the help of @fneum and github's description for PR and issue templates.
Using templates from PyPSA-EUR and the [Open Source Templates tale](https://www.talater.com/open-source-templates/#/).
For completness, ease of use and mental-aid - we're humans and tend to forget about things.
n/a
> Add PR and issue templates.

- .travis.yml
- README.rst
- environment.yaml
- test/test_dummy.py
- Runs tests
- Deploys new tags on master to PyPI
@fabianhofmann:
I activated travis on atlite. So i'd suggest, merging this into master, then rebasing the `v0.0.3` branch ontop of it. Merging the release branch when it is ready to master.
And then going to https://github.com/PyPSA/atlite/releases and "Draft a new release" to generate the new tag and thus push the release to pypi. If that works I'd add the same to vresutils so that all of you should be able to create new releases.
> Add travis-ci configuration

- test/test_creation.py
- test/test_preparation_and_conversion.py
> tests: Use pytest fixtures and marks

- .travis.yml
Token and url are expected to be configured as an environment variable in travis.
(which I already did)
> travis: Add cdsapi token

- atlite/convert.py
- test/test_preparation_and_conversion.py
This PR fixes the capacity returned by the convert & aggregate function. It also adds a test for exactly this case.
> Fix capacity in convert and aggregate function

- .travis.yml
- atlite/data.py
- atlite/datasets/era5.py
- environment.yaml
fixes #107 
Note: for mysterious reasons the tempfile deletion has problems on windows machines, a nice workaround is to use a wrapper which pulls tempfile creation and deletion out of the prepare function. This works
> Windows machine fix

- atlite/pv/orientation.py
Fixes #103 .
Untested yet. Await response by @WeselyDAN .
> Support negative latitudes to PV panel orientation

- atlite/convert.py
- test/test_preparation_and_conversion.py
fixup for all input combinations to `convert_and_aggregate`. Before there occured an error when a `matrix` without `layout` argument was given.
> Convert fix

- RELEASE_NOTES.rst
- atlite/gis.py
- atlite/hydro.py
- atlite/utils.py
- doc/environment.yaml
- environment.yaml
- test/test_gis.py
> Use tqdm progressbar for better display

- test/test_preparation_and_conversion.py
Due to weird behavior of netcdf files on windows machines...
> test: sit out one test on win machines

- setup.py
Closes # (if applicable).
Add `toolz` package to `setup.py` in `extras_requires[doc]`.
```
WARNING: autodoc: failed to import class 'Cutout' from module 'atlite'; the following exception was raised:
No module named 'tlz'
WARNING: autodoc: failed to import module 'data' from module 'atlite'; the following exception was raised:
No module named 'tlz'
WARNING: autodoc: failed to import module 'convert' from module 'atlite'; the following exception was raised:
No module named 'tlz'
WARNING: autodoc: failed to import module 'resource' from module 'atlite'; the following exception was raised:
No module named 'tlz'
WARNING: autodoc: failed to import module 'wind' from module 'atlite'; the following exception was raised:
No module named 'tlz'
```
API reference does not show: …
> add toolz package for api reference

- RELEASE_NOTES.rst
- atlite/gis.py
Related to https://github.com/PyPSA/pypsa-eur/issues/249
> set multiprocess context to 'spawn'

- .pre-commit-config.yaml
This PR adds a pre-commit action for REUSE compliance check.
Easier, automated checks for REUSE compliance.
Locally.
> Add pre-commit action for REUSE compliance check.

- README.rst
- atlite/cutout.py
- test/test_gis.py
the pre-commit.ci CI will automatically run pre-commit config via CI pre-commit-ing PRs.
TODO: Add correct link to pre-commit.ci badge. @fneum 
n/a
n/a
Easier than GitHub Actions.
In different repository.
> Add CI (pre-commit.ci) for running pre-commit as CI

- .github/workflows/CI.yaml
- .github/workflows/deploy.yml
Move the CI to GH Actions. Current but temporary downside, skip tests on windows machines. 
GH is faster and more responsive.
> GH Actions CI

- atlite/datasets/gebco.py
- atlite/hydro.py
- atlite/resource.py
- test/test_gis.py
- test/test_preparation_and_conversion.py
- test/test_resource.py
Solves #156 
Effective code coverage, after removing cordex.py, ncep.py and deprecated functions
```
----------- coverage: platform linux, python 3.8.5-final-0 -----------
Name                             Stmts   Miss  Cover
----------------------------------------------------
atlite/__init__.py                   7      0   100%
atlite/aggregate.py                 11      2    82%
atlite/convert.py                  153     25    84%
atlite/cutout.py                   164     18    89%
atlite/data.py                      83      4    95%
atlite/datasets/__init__.py          2      0   100%
atlite/datasets/era5.py            136     15    89%
atlite/datasets/gebco.py            27      1    96%
atlite/datasets/sarah.py            86      2    98%
atlite/gis.py                      234 …
```
> add tests for better code coverage, fix some deprecations

- atlite/cutout.py
- atlite/utils.py
- doc/conventions.rst
- doc/index.rst
Closes #162 
Add a `Conventions` section to the documentation. 
Clarification on how atlite's data structure works. 
local build of the docs
> add conventions section to the documentation

- pyproject.toml
- setup.py
Closes #191 
Closes #192 
Update dask requirements, set scm requirement through pyproject.toml as recommended by https://pypi.org/project/setuptools-scm/
> update dask requirements, remove scm requirement

- atlite/convert.py
- test/test_dynamic_line_rating.py
> Line rating units

- atlite/convert.py
- atlite/datasets/era5.py
Closes # (if applicable).
Fixed data error in era5.py due to wrong data format
Added solar radiance heat losses due to angle difference of transmission line and sun in convert.py
For more accurate calculation of heat gain in transmission lines
- [ x] Small bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] I tested my contribution locally and it seems to work fine.
> changes to solar radiance + small bug fix

- test/test_dynamic_line_rating.py
Some tests were inadequate, using the combined series resistance as single wire resistance
> test: revise line rating tests

- atlite/gis.py
> fix: use explicit rasterio resample method for averaging

- README.rst
- RELEASE_NOTES.rst
- doc/contributing.rst
- doc/index.rst
> add discord reference

- RELEASE_NOTES.rst
- atlite/gis.py
https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview
> era5: back extension to 1940

- doc/examples/more_examples.rst
- doc/installation.rst
- doc/support.rst
Fix broken links to repo and Discord server in documentation
> Fix broken links 

- environment.yaml
- setup.py
xref #363 
and also some tests were super slow
to be investigated
> temporarily limit numpy version to <2

- .github/workflows/CI.yaml
Secret `CDSAPI_TOKEN_BETA`has been added to the repository.
> CI: use CDS BETA

- atlite/datasets/era5.py
- environment.yaml
- setup.py
> limit to cdsapi>=0.7,<0.7.3

- atlite/pv/solar_position.py
> fix: handle mismatched dim lengths during rechunking

- .github/workflows/test.yaml
- atlite/resource.py
- Runs daily cron job to retrieve cutouts only on single matrix job
- Adds workflow_dispatch trigger to allow for manual run without cache
> test: improve caching

- atlite/__init__.py
- removing version assert, since people struggle with it when they not pull with tags
> remove version assert

- .github/workflows/release.yml
- .github/workflows/test.yaml
- Trigger tests before release
- Especially needed for release branches
> ci: trigger tests before release

- .pre-commit-config.yaml
> code: Set pre-commit autoupdate to quaterly schedule

- .github/workflows/test.yaml
- atlite/datasets/era5.py
Maybe this fixes the miracle in #442
>  ci: use environment variables for CDS API configuration
