PyPSA/atlite

atlite/convert.py

Previously matrices with a single entry created a 0d numpy array, causing a ValueError in xr.DataArray(...) creation.
By reshaping instead of squeezing, a 1D array is enforced.

Bugfix: Allow matrices with a single bus entry.

---

atlite/pv/solar_position.py

Machine eps causes values slightly below -1. and above +1. ; these
values result in NaN values from the following arcsin which in return
cause warning from comparison of the cosincidence matrix.
Clipping removes the additional +/- eps.

Prevent warning from arcsin(..) and cosincidence comparison

---

atlite/convert.py
atlite/resource.py
atlite/wind.py

Logically the two actions (wind speed extrapolation and conversion) are independent steps - this is represented by the separation.
Minor: In the same go, change from numpy.interp to xarray.interp

(Refractor) Wind speed extrapolation into new module

---

atlite/resource.py

If we do not set the rated power after smoothing a turbine curve, the per unit calculation in convert_wind(..) will not be correct. Instead we would be introducing a 'hidden factor'.
(as described by
Norgaard, Per, and Hannele Holttinen. "A multi-turbine power curve approach." Nordic wind power conference. Vol. 1. Chalmers, 2004. )

(Fix / Sci) set rated power for smoothed turbines

---

environment.yaml
setup.py

Geopandas became a necessary lib with the hydro module (7837f984a6dbb0c42a7adf91dc421835ab023bf0).

Fix dependencies to include geopandas

---

atlite/data.py

Internal variable. No longer available in Python 3.7
see here:
https://github.com/python/cpython/commit/d8ac4d1d5ac256ebf3d8d38c226049abec82a2a0?diff=unified

V0.2 fix ast._NUM_TYPES usage.

---

atlite/convert.py
atlite/resource.py
atlite/wind.py

As stated in #21 , this change provides an adapter for downloading into `resources/windturbine` (more precisely `atlite.config.windturbine_dir`) and using the data from OEDB.
```
def download_turbineconf(requested_turbine=None):
"""Download a windturbine configuration from the OEDB database.
Download the configuration of a windturbine model from the OEDB database
into the local 'windturbine_dir'.
The OEDB database can be viewed here:
https://openenergy-platform.org/dataedit/view/supply/turbine_library
(2019-07-22)
Only one turbine configuration is downloaded at a time, if the 
search parameters yield an ambigious result, not data is downloaded.
Parameters
----------
requested_turbine : dict
Search parameters, either provide the turbine model id (takes priority)
or a manufacturer and …
```

Provide oedb adapter for downlading wind turbine configs.

---

atlite/convert.py

*After enabling warnings, I was swarmed with the deprecation warning on `cutout.meta` being deprecated in favour of `cutout.data`.*
Please check if the code intention was correctly transferred.
I did a quick run of the code against my limit scenario and it seems to work.

convert: Substitute deprecated cutout.meta with cutout.data.

---

atlite/utils.py

* On trying to automatically migrate an existing cutout, display the correct (new) order (min,max) for coordinates in the cutout recreation command.
* Use the logging.error(...) facilities to correctly categorise the MergeError incl. the stack trace.

utils: Correct error message for cutout migration.

---

atlite/convert.py

From xarray version 0.15.1, .values cannot be assigned. You should
use the .assign_coords() method instead.
See release notes for xarray 0.15.1 "breaking changes":
http://xarray.pydata.org/en/stable/whats-new.html#v0-15-1-23-mar-2020

convert: Fix heat demand hourshift for xarray 0.15.1

---

atlite/datasets/era5.py

Since the big PR for v0.2 is already super big, I do it this way. Probably this is a good procedure for the upcoming fixes.
Fix cutout creation for odd bounds with `era5`
closes #64

Fix cutout creation with odd bounds (era5)

---

atlite/cutout.py

As discussed with @euronion, we want to ensure backward compatibility for bounds with `x0 > x1` or `y0 > y1`
This change ensures the correct ordering of bounds.

ensure correct ordering of slices

---

atlite/datasets/era5.py

As discussed in #62 the grid alignment of era5 datasets when `module=sarah` is swapped for the y-axis. This fixes the alignment for all datasets produced by era5.
closes #62

fix era5 grid alignment

---

atlite/cutout.py
atlite/data.py
atlite/gis.py
atlite/utils.py
test/test_cutout_preparation.py

Shapely provides its own 'rtree' for filtering out shapes which cannot intersect with each other. 
This change includes the [shapely.ops.strtree functionality](https://shapely.readthedocs.io/en/latest/manual.html#strtree.STRtree). Therefore the backup code in `compute_indicatormatrix` is obsolete. 
The speed gain is about 90%

use shapely's strtree instead of rtree

---

MANIFEST.in
atlite/__init__.py
atlite/_version.py
setup.py

Uses [setuptools_scm](https://github.com/pypa/setuptools_scm) to:
- compute a version number based on the latest git tag
- write it to `atlite/version.py`
- superseed MANIFEST.in (auto-generated by listing git repo)
No need to adapt `_version.py` anymore.

setup: Use git tag versioning

---

atlite/data.py
atlite/datasets/era5.py
atlite/datasets/sarah.py

Since queueing time is dominant for downloading from ERA-5, I'd propose
to at least have some parallelized support for queueing.
This PR ...
- fixes two bugs with `era5.retrieval_times`
- re-enables warnings
- adds per-dataset dask.delayed concurrency
- introduces a lock to keep progress bars from breaking one another
Would be an alternative for #86 . But might not fix the original reason for it.

data: Re-enable parallelized queueing

---

atlite/convert.py
atlite/pv/irradiation.py
atlite/pv/solar_panel_model.py

This PR fixes RuntimeWarnings caused by dividing with zero. Before these were suppressed by np.errstate which however is ignored by dask.
solves #55

Fix divisions by zero

---

atlite/convert.py

PROJ >=v7.0 is default on conda-forge now, which impacts the version of pyproj which atlite installs (>=v2.5). In fact, PROJ <=v7.0 is no longer on the `main` channel on conda-forge. This means that more information is required to reproject to Albers Equal Area. I've designed it to choose the AEA parameters based on the bounds of the input shapes, but this projection (and any equal area one) is liable to distortion if the bounds become too large (~few thousand km, I believe).
This PR fixes the following error raised when using the `conversion.hydro` method with a fresh install of atlite 0.0.3:
```python
File "/path/to/atlite/convert.py", line 551, in hydro
runoff *= (1000. / 24.) * xr.DataArray(basins.shapes.to_crs(dict(proj="aea")).area)
File "/path/to/geopandas/geoseries.py", line 531, …
```

Add PROJ>=7 valid 'aea' projection string

---

atlite/datasets/era5.py

The recent back extension of the ERA5 from 1950-1978 has a different product name. This is accounted for in this PR.
https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels-preliminary-back-extension?tab=overview

add support for ERA5 back extension to 1950

---

atlite/cutout.py
atlite/data.py
test/test_preparation_and_conversion.py

As soon as a cutout is already created, the underlying cutout parameters should be immutable. With this, atlite warns about ignoring cutoutparams, if they are passed anyway.    
Secondly, fix Cutout.prepared and undo its deprecation

Modified cutout creation

---

atlite/cutout.py
atlite/data.py

The previous behavior that the prepared_feature series was build from a lookup list only was not secure for cutouts with mixed modules. This makes the function robust

data.py set "feature" attribute for every variable

---

atlite/cutout.py
test/test_preparation_and_conversion.py

Enable to merge two different cutouts. Add function `to_file()` for explicitly writing out cutout.

Cutout merge

---

RELEASE_NOTES.rst
atlite/cutout.py
atlite/datasets/era5.py
atlite/gis.py
test/test_preparation_and_conversion.py

ERA5 coordinates have dtype float32. When merging into the cutout, this causes a corruption of the cutout coordinates. This only applies for dx and dy unequal to 0.25.

Fix coordinates corruption ERA5

---

RELEASE_NOTES.rst
atlite/convert.py

Add a new argument to `convert_and_aggregate` which is passed to dask.compute. This allows to properly set i.e. the number of workers (threads).

Allow passing dask keyword arguments in conversion functions

---

RELEASE_NOTES.rst
atlite/gis.py
test/test_gis.py

Fix `regrid` function in `atlite.gis`. The previous implementation set an affine transform starting at the center of a cell at the origin. The corrected transform starts at the real origin (origin of the origin cell). Further a padding of the extent ensures that all values are taken into account in the target projection. 
New tests for the `pad_extent` function were added.
```python
cutout = atlite.Cutout(path="sample",
x=slice(20, 32), y=slice(33, 45),
module="sarah",
time=slice("2013-01-01", "2013-01-03"),
sarah_dir='sarah_dir',
sarah_interpolate=False,
)
cutout.prepare()
```
in master produces:
Watch out for the dark edges. 
The corrected version produces (using the same code)

Fix data `atlite.gis.regrid`

---

atlite/cutout.py
atlite/gis.py

The rasterio (or GDAL) average downsampling returns different results dependent on how the target raster (the cutout raster) is spanned. Either it is spanned from the top left going downwards, .g. Affine(0.25, 0, 0, 0, -0.25, 50), or starting in the lower left corner and going up, e.g. Affine(0.25, 0, 0, 0, -0.25, 50). Here we stick to the top down version which is why we use `cutout.transform_r` and flipping the y-axis in the end.

Cutout transform downwards

---

RELEASE_NOTES.rst
atlite/cutout.py
test/test_gis.py

Adjust `Cutout.extent` to cover the whole cutout area. Before, it indicated the coordinates of the centers of the corner cells. 
Add a `Cutout.bounds` property. The extent is now a numpy array.

cutout: adjust extent, add bounds propoerty

---

RELEASE_NOTES.rst
atlite/data.py

Closes #128 
This change is necessary for compatibility with the newest xarray version v0.17. 
Has to be checked on a windows machine with xarray v0.16.0, @euronion could you do this (just running pytest)?

Try closing .nc file only through ds.close()

---

RELEASE_NOTES.rst
atlite/datasets/sarah.py
atlite/gis.py
test/test_gis.py
test/test_preparation_and_conversion.py

* Fix the ``regrid`` function in ``atlite.gis`` for target coords which are not having the same bounds as the original ``xarray.Dataset``. The previous implementation was leading to a small shift of coordinates in the preparation of SARAH data.
* Fixed sarah data for a time frequency of 30 minutes. This was raising an assertion as is the (new) pandas frequency string for 30 minutes is '30T' not '30min'.
* Fixed sarah data for ``dx = dy = 0.05``. Due to the float32 dtype of the sarah coordinates, the cutout coordinates were corrupted when merging. This was fixed in the sarah module by converting the coordinates to float64. This also speeds up the cutout creation for more coarse grained cutouts.  
Additional tests were added.
- ~I have adjusted the docstrings in the code appropriately.~
- …

SARAH: fix fine grained resolution

---

RELEASE_NOTES.rst
atlite/cutout.py

The function ``layout_from_capacity_list`` was added to the cutout class. It calculates the aggregated capacities per cutout grid cells (layout) based on a list of capacities with coordinates, e.g. list of wind turbines.

add function for capacity layout

---

RELEASE_NOTES.rst
atlite/data.py

Closes #147
Make attribute update robust against duplicated entries.  Only relevant for xarray >= 0.18

fix attribute update

---

doc/introduction.rst
examples/create_cutout_SARAH.ipynb
examples/historic-comparison-germany.ipynb
examples/landuse-availability.ipynb

Closes #160 
Some spelling and duplication fixes in the doc

minor doc fixes

---

RELEASE_NOTES.rst
atlite/convert.py

This addresses the issue brought up by @lisazeyen off-list, where `atlite` did not consder restriction on the amount of threads used. The problem was caused by a missing passthrough of `dask_kwrds`.
Fix problem.
see summary above.
No issue to link.
Not yet.

Fix dask_kwrds being ignored during if only capacity_layout is created in convert_and_aggregate.

---

RELEASE_NOTES.rst
atlite/gis.py
test/test_gis.py

Doc-string change for `ExclusionContainer.add_raster(...)` and changes to tests:
Anonymous functions are not permitted for the `codes=...` keyword argument.
Non-anonymous functions can be used. As an example I've changed the related test (which was for the meantime inactive) from a lambda function to an equivalent formulation using `functools.partial` and `np.greater_equal`.
Anonymous functions lead to complications with python's `multiprocessing`, c.f. https://github.com/PyPSA/pypsa-eur/issues/249 .
n/a
- [n/a ] New feature (non-breaking change which adds functionality)
- [n/a] Breaking change (fix or feature that would cause existing functionality to change)
- [n/a] I have documented the effects of my code changes in the documentation `doc/`.
- [n/a] I have added newly introduced …

Add note to ExclusionContainer.add_raster(...) that anonymous (lambda) functions are not permitted.

---

atlite/datasets/era5.py
test/test_preparation_and_conversion.py

Change the cds variable name "orography" to "geopotential". 
According to https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation "orography" is a valid variable name, but in the cdsapi it returns no data error. This might be a temporary thing due to problems on the era5 server. It didn't raise an error so far, as the cutouts of the test scripts were "kept warm" by the cds server.  
Note: if the problem resolves automatically, I'd say we kill this PR, but if not, it provides remedy.

ERA5: rename "orography" variable to "geopotential"

---

examples/create_cutout.ipynb

Added a notice about the  CDS side processing time in the create_cutout example including a link where to 
check the status of CDS request. To inform about why it might take a while before the download starts.
Motivated by #175

add notice about processing time CDS

---

doc/conf.py

fix error in the css file configuration due to incompatibility with new version of sphinx-rtd-theme

doc: fix css overwriting file

---

RELEASE_NOTES.rst
atlite/convert.py
atlite/pv/solar_panel_model.py
atlite/resources/solarpanel/CSi.yaml
atlite/resources/solarpanel/CdTe.yaml

I'm not 100% satisfied with the PR, it feels a bit hacky. Nevertheless...
Explicitly provide units and a name for returned DataArrays created by `.wind(...)` and `.pv(...)` function.
For `.wind(...)` the location to set name and unit is straightforward.
For `.pv(...)` I'm not an expert for the Boilfinger model and couldn't find the correct location; I would assume the unit is identical to the Huld model, but since I am not 100% sure I decide to set unit and name inside the specific model.
Inside `.convert_and_aggregate(...)` where the DataArrays are manipulated the unit/name are either changed or keeping of the attributes is made explicit via `keep_attrs=True` (otherwise they would be implicitly removed by `xarray`).
Caveat: Setting of units relies on some conventions, e.g. for the units …

Explicit units and meaning of returned DataArrays

---

atlite/datasets/sarah.py

Cutout creation with SARAH yields the following warning:
```
atlite/atlite/datasets/sarah.py:72: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
if (start < files.index[0]) or (end.date() > files.index[-1]):
```
This is adressed by this PR.
remove `.date()` from comparison which doesn't seem to be needed anyways, as timestamps are compared.

Adress future warning for SARAH cutout creation.

---

RELEASE_NOTES.rst
atlite/datasets/era5.py
atlite/datasets/sarah.py
atlite/pv/solar_position.py

Closes #158 .
* Solar position will be calculated during cutout creation
* `atlite.pv.solar_position.SolarPosition` results become part of the `"influx"` feature
* Solar position for ERA5 is calculated with an time-shift of "-30min" to take into account the fact that ERA5 variables are aggregated (right interval border, see #158 )
* `atlite.pv.solar_position.SolarPosition(...)` is backwards compatible (for now) and acts as a pure getter if the variables are present in the cutout, else it calculates them.
Tested locally on two cutouts (one ERA5, one SARAH)

Calculate solar position already during cutout creation + add time-shift for ERA5

---

setup.py

chunksizes (used by new Solarposition function) requires xarray >= v0.20

update xarray version

---

atlite/convert.py
test/test_dynamic_line_rating.py

I do not know why but apparently the CI tests in PR #206 were not triggered. This is why a wrong setup of the tests sneaked in. 
Changes proposed
* convert.py: fix line rating for dictionary input
* test line rating: add solar azimuth/altitude to dicts

hot fix for dynamic line rating tests

---

atlite/convert.py

There is a small mistake in the natural convection equation. It is supposed to be the square root of rho.

correct equation natural convection

---

RELEASE_NOTES.rst
atlite/convert.py
atlite/datasets/era5.py
atlite/datasets/sarah.py
atlite/pv/irradiation.py
atlite/pv/solar_position.py
test/test_dynamic_line_rating.py

Closes #212 
Touches #211 
Initial attempt was to solve #211, but is turns out to be tricky. The problem is that the era5 module relies on get_<feature> functions which take the era5 retrieval parameters as an argument. The SolarPosition function however requires a dataset with the complete set of coordinates. It would be necessary to pass the `cutout.data` as an argument to the `get_solar_position` function. This requires changes one have to think through a bit. 
The same counts for the sarah module. Its `get_data` function does not use the `feature` argument so far. It would be necessary to make separate `get_influx` and `get_solar_position` functions. I would postpone that change to another time. 
In order to make the `influx` feature still a bit handier, I removed the solar …

purge influx feature 

---

RELEASE_NOTES.rst
atlite/datasets/sarah.py

Fix a bad comparison when creating cutouts with SARAH2 data.
Previously if the cutout was to be created for e.g. an upper end of "2013-12-31 23:00" and the `sarah_dir` did only contain datafiles for 2013 (i.e. labelled "xxx20131223yyy.nc"), then the comparison failed and the error was thrown.
This bug was not discovered because we had previously always downloaded multiple SARAH2 dataset years, i.e. more than 2013 were contained in the same directory and the bug did not surface.
Fixing this here.
Locally. New cutout with SARAH data created.

Fix bad comparison for sarah datafiles.

---

RELEASE_NOTES.rst
environment.yaml

Closes #238 .
The problem and solution are described in issue https://github.com/PyPSA/atlite/issues/238
I run **pytest** before and after the changes. See more about my reproducable testing procedure here -> https://github.com/PyPSA/atlite/issues/238
- [NA] I have documented the effects of my code changes in the documentation `doc/`.

Fix rasterio reprojection bug. Appears with 1.2.10

---

RELEASE_NOTES.rst
atlite/hydro.py

Closes #241 
This PR aims at avoiding NaN values into the inflow.
Any NaN value would be converted into 0.0 instead before summing to the inflow.
When performing the shift of the inflow dataarray, some NaN values appears hence leading to NaN values into the sum.
This has been fixed.
If NaN values remain, this may lead to issues in the usage of the tool
Using pypsa-africa

Fix NaN values into inflow

---

RELEASE_NOTES.rst
atlite/gis.py

Improving the efficiency of `shape_availibility()` with respect to memory load through changes in dtypes and the method of mask summation.  
Two main changes are made to reduce the memory load while running `shape_availability()` within gis.py:
-  dtype transformations via `np.astype()` to `int32` are removed on several occasions to keep matrices returned from functions as `rasterio.features.geometry_mask()` and `scipy.ndimage.morphology.binary_dialation()`  in dtype `bool`. 
The dtype transformation to `float64`, applied to the final mask that is returned by the function, is removed.
-  Instead of saving individual masks for every exclusion raster or geometry to a list and summing them on the return, a new method is introduced, which adds the masks on every loop iteration. This is done …

Improve memory load efficiency for shape_availability calculation

---

atlite/gis.py

ERA5 stable reanalysis product has been extended to data from 1959 onwards (https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels).

gis: extend allowed time frame to 1959

---

RELEASE_NOTES.rst
environment.yaml
setup.py

As noted in PR https://github.com/PyPSA/atlite/pull/240, for performance and stability gains it makes sense to move to the **now** available 1.3.0 version. 
Change the environment rasterio version to be >1.2.10
Description of Rasterio 1.3.0 release: https://github.com/rasterio/rasterio/releases
`pre-commit run --all`

Rasterio update to 1.3.0

---

.gitignore
RELEASE_NOTES.rst
atlite/datasets/era5.py
test/test_preparation_and_conversion.py

Fixes a bug in solar position time shift for ERA5 influx data where for some cases the frequency of the data would be incorrectly inferred. The change always shifts by -30 minutes, regardless of the sampling of the data. See discussion in https://github.com/PyPSA/atlite/issues/256#issuecomment-1268473262 for reasoning.
Closes #256
* The [first commit](c190c3410b037e278a632322dff400311e925bb8) in the pull request introduces a [failing unit test](https://github.com/zoltanmaric/atlite/blob/90c593142371d9a2a9c97e5a13d5d128594a84cc/test/test_preparation_and_conversion.py#L501-L504) that demonstrates the bug reported in #256.
* The [second commit](90c593142371d9a2a9c97e5a13d5d128594a84cc) fixes the bug by always shifting by 30 minutes (removing the inference of the frequency of the data)

Always shift solar influx by 30 minutes

---

RELEASE_NOTES.rst
atlite/hydro.py

In hydro.py, line 103
`nhours = (distances * (flowspeed * 3.6) + 0.5).astype(int)`
should be
`nhours = ((distances * 1000) / (flowspeed * 3600) + 0.5).astype(int)`
or
`nhours = (distances / (flowspeed * 3.6) + 0.5).astype(int)`

hydro inflow unit conversion corrected

---

atlite/resource.py
doc/release_notes.rst

Closes #227.
Methods ``get_windturbineconfig``, ``get_solarpanelconfig`` and ``get_cspinstallationconfig`` load yaml files based on the passed
configuration name. Now, additionally, the methods recognize if a path to a locally stored config is passed.
The file is then loaded instead of a predefined config.
The methods run ``Path([the local path]).exists()`` to check if the path exists. If not, the methods assume that the user passed 
the name of a config, and proceeds as before the change.
This is a small change, proposed a while ago by @fneum. I seems like a sensible addition.
I checked all three functions to make sure that both old and new behaviour are behaving as expected.

Issue227 - Turbine, Panel and CSP Installation Configs from local path

---

environment.yaml
setup.py

Only 1.2.10 created issues in Atlite see https://github.com/PyPSA/atlite/pull/240. 
My last stable PyPSA-Earth environment required rasterio 1.2.9.
So suggestion to ease restriction

ease rasterio restriction

---

RELEASE_NOTES.rst
atlite/datasets/era5.py
test/test_preparation_and_conversion.py

Closes #190.
Requesting cutout data spanning recent (ERA5T) and data older than ~3 months (ERA5) results in an additional dimension in `cutout.data`, called `expver`, which `atlite` currently cannot handle gracefully.
This change collapses the two dimensions into a single dimension.
See details in #190.
The first commit of this pull request introduces a failing test that demonstrates the bug. The second commit fixes the bug and makes the failing test pass.
~**IMPORTANT**: the test introduced in the first commit **should not be merged** into `master`. The test data is time-dependent. Data which is ERA5T today will become ERA5 in the future. I only added the test for illustration. See the discussion in this pull request for alternative test proposals.~ (This has been resolved)

Combine ERA5 and ERA5T data

---

RELEASE_NOTES.rst
atlite/cutout.py

The function are deprecated since version v0.2.1

remove deprecated grid functions

---

.github/workflows/CI.yaml
.github/workflows/deploy.yml

Let's update to a newer Python version
Bumping Python version for CI from 3.8 -> 3.11
Bumping ubuntu version from 18 -> latest for pypi and conda deploy action
- [/] Bug fix (non-breaking change which fixes an issue)
- [/] Breaking change (fix or feature that would cause existing functionality to change)

Bump Python and Ubuntu versions

---

atlite/convert.py

Simple fix of nan values in hydro function.
In the hydro function a normalization of the matrix indicator is performed; yet some nan values may be created.
To avoid the formation of nan values, in this PR they are forced to zero.
This is a feature needed for earth analysis and originally implemented intp #245.

Add fix nan

---

RELEASE_NOTES.rst
atlite/convert.py
atlite/resource.py
test/test_resource.py

Closes #314
First proposal to fix #314. It is still to discuss if the appended cutoff wind speed should be slightly higher than the last entry in the power curve. Currently, np.interp will lead to 0 if the exact cutoff wind speed is met.
- `convert_wind()` function throws a warning if the power curve has no cutoff for high wind speeds i.e. if the last value is not zero.
- `Cutout.wind()` method now has a new argument `add_cutoff`. When set to True, this will modify the power curve by inserting a zero at the highest wind speed in the power curve. 
see #314.
Not really yet.

fix: power curves with missing cutoff

---

RELEASE_NOTES.rst
atlite/cutout.py
test/test_creation.py
test/test_gis.py

- add functions `area` & `layout_from_area_density`
- allow for `auto` chunks when loading cutout
The ``area`` function is helpful for custom workflows, the same with the new layout function.
The auto chunking **can** help to accelerate the computation of the conversion functions.

Add helper function ``area`` and ``layout_from_area_density`` & allow auto chunks

---

atlite/convert.py
doc/release_notes.rst

It can be useful to get access to the hourly capacity factor per grid cell. 
this small addition to convert_and_agregate allows it.

CF timeseries per gridcell

---

atlite/gis.py

The function `compute_availabilitymatrix()` includes an option to disable the progress bar (`disable_progressbar`). However, for non-parallel computation path (i.e., when `nprocesses` is `None`, the code uses `tqdm` directly, w/o passing the `disable_progressbar` check.  This PR fixes it. User is informed if progress bar is disabled.
Why bother: it seems that **progress bar makes computation much slower**. For a test case (UA, solar availability matrix, local computation, nprocesses is None) disabling progress bar speeds the process from **2000 seconds to 760 seconds.** 
Similar behavior was observed for other atlite processes, such as `build_renewable_profiles` (rumor evidence).
Closes #[pypsa-eur/1090](https://github.com/PyPSA/pypsa-eur/issues/1090)

fix: disable_progressbar in compute_availabilitymatrix

---

atlite/datasets/sarah.py
atlite/pv/orientation.py
test/test_creation.py
test/test_preparation_and_conversion.py

Completely move the temporal specification from "H" to "h".

fix hour specs from deprecated "H" to "h"

---

atlite/datasets/era5.py

closes #361 
This PR is backwards compatible; old CDS infrastructure can still be used.
Other things needed to update:
- follow instructions https://forum.ecmwf.int/t/the-new-climate-data-store-beta-cds-beta-is-now-live/3315
- retrieve new `~/.cdsapirc`
- update to `cdsapi>=0.7.0`
Main changes:
- The time variable was renamed in CDS from "time" to "valid_time", which is renamed in `_rename_and_clean_coords()`
- A useless "number" coordinate was added, which is removed in `_rename_and_clean_coords()`.
- There was some weirdness in the "expver" coordinate when ERA5 and ERA5T data were mixed (coordinate but not a dimension). Also, it seems that the "expver" coordinate is now always created and is a 4-digit string rather than an integer. If somebody has a leaner suggestion here, I am all …

era5: update to new CDS infrastructure

---

RELEASE_NOTES.rst
atlite/convert.py
atlite/data.py
atlite/datasets/era5.py
atlite/datasets/gebco.py
atlite/datasets/sarah.py
atlite/gis.py
atlite/hydro.py
test/test_preparation_and_conversion.py

Closes #371.
Adds option to toggle whether ERA5 downloads are requested in monthly or annual chunks with option to place concurrent requests with keyword argument `cutout.prepare(monthly_requests=False, concurrent_requests=False)`.
Potential performance improvements and functionality tests shown in #371.

toggle for (concurrent) monthly ERA5 requests; progressbar disabled by default 

---

RELEASE_NOTES.rst
atlite/convert.py
atlite/csp.py
atlite/datasets/era5.py
atlite/pv/irradiation.py
atlite/pv/orientation.py
atlite/pv/solar_position.py
atlite/resource.py

I had hoped for some performance gains, but this is not so clear.

use dask.array functions instead of numpy

---

.github/workflows/test.yaml
test/conftest.py
test/test_gis.py
test/test_preparation_and_conversion.py

- Adds the option to use a cache dir for cutout retrieval instead of `tmp_path_factory` for every run
- Used to decrease load during tests in CI  
- Pass it via the optional `--cache-path` flag
- e.g. `pytest . --cache-path ./.cutout_cache`

test: cache retrieved cutouts

---

atlite/datasets/era5.py

The changes made in #261 (#190) are no longer needed with the new CDS API. expver` is now a coordinate mapping on the time dim instead of being a separate dim.
I haven't worked with the API before, so it would be great if you could confirm @zoltanmaric @FabianHofmann

fix: ERA5T dimension merge

---

atlite/datasets/era5.py
pyproject.toml

Follow up to a workaround introduced by @euronion in #236 for an encoding issue in xarray (https://github.com/pydata/xarray/issues/7691), which was fixed by (https://github.com/pydata/xarray/pull/8713) and eventually included xarray v2024.03.0 (https://github.com/pydata/xarray/releases/tag/v2024.03.0).

fix: Skip previous encoding workaround for fixed xarray versions

---

atlite/convert.py
atlite/datasets/era5.py
atlite/resource.py
atlite/wind.py
pyproject.toml
test/test_preparation_and_conversion.py

Closes #231 .
Refer to issue for context. Implements the power law interpolation method as a new argument
to `cutout.wind`. Needs to be chosen manually for now.
A suggested in the issue we retrieve 100m and 10m wind speeds and then calculate a wind shear exponent from those during cutout preparation.
Looks like the power law is preferred at least for turbine heights above wind blending (?) height (70m?). So this should most likely become the new default if we have 100m wind speeds available (as we have for ERA5). 
TODOs:

feat(wind): Add power law interpolation method for wind conversion

---

atlite/cutout.py

docs: minor fixes in the docstrings for Cutout

---

atlite/convert.py
atlite/cutout.py
doc/introduction.rst
doc/release_notes.rst

The PR adds implementation of cooling demand similarly as it's done for heating

Add cooling demand

---

RELEASE_NOTES.rst
pyproject.toml

This is a bit of a random find, but caused some significant faults in renewable potential calculations...
Versions 1.4.0 and 1.4.1 or `rasterio` cause a flipped y-axis in `cutout.compute_availabilitymatrix()`, which neither earlier nor later versions of `rasterio` do. With no changes but changed rasterio version:
I think excluding these versions makes more sense than implementing version-specific behavior in `atlite`.

rasterio 1.4.0/1.4.1 flips y-axis in `compute_availabilitymatrix`

---

atlite/convert.py
doc/release_notes.rst

Removed unnecessary factor of 1000/24 from the runoff calculation, as pointed out by user JKALanger. The function now correctly calculates runoff in m3 per hour by directly multiplying the depth (in meters per hour) by the basin area (in square meters).
Closes # (if applicable).

Fix incorrect unit conversion in hydro function in convert.py
